version: "3.7"
services: 
  app:
    build: .
    image: opencv
    container_name: opencv
    environment: 
      - DISPLAY=docker.for.mac.host.internal:0
    volumes:
      - ./imgs:/home/imgs
      - ./bin:/go/bin
    tty: true